name: JavaScript FaaS
version: 0.0.1
description: Node.js function runtime for cloud events
license: Apache-2.0
language: JavaScript
maintainers:
  - name: Lance Ball
    email: lball@redhat.com
    github-id: lance
default-template: default
