name: JavaScript FaaS
version: 0.0.1
description: JavaScript Function Runtime
license: Apache-2.0
language: JavaScript
maintainers:
  - name: lkingland
    email: lkingland2038@gmail.com
    github-id: lkingland
default-template: simple
