name: JavaScript FaaS
version: 0.0.1
description: JavaScript Function Runtime
license: Apache-2.0
language: JavaScript
maintainers:
  - name: Lance Ball
    email: lball@redhat.com
    github-id: lance
default-template: simple
