version: 2
general:
  branches:
    only:
      - ci # TODO: Change this once we have CI building correctly
jobs:
 build:
   machine:
    image: ubuntu-1604:201903-01
   steps:
     - checkout
     - run: ./ci/install_appsody.sh
     - run: make test
